server:
    servlet:
        context-path: /finance

spring:
    jpa:
        database: POSTGRESQL
        show-sql: true
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres
        url: jdbc:postgresql://192.168.68.116:5432/casa
    kafka:
        bootstrap-servers: 192.168.68.116:9092